-- Nested-entity refactor (Path B) — extend the schema layer so docs
-- with repeated structures (bank statements with transactions,
-- invoices with line items, contracts with clauses) are stored as
-- one doc-root entity + N typed child entities, instead of being
-- flattened into a single placeholder "Doc" with key-value fields.
--
-- This migration is ADDITIVE — no drops yet. Drops happen at 0038
-- once readers/writers are migrated.
--
-- Three changes:
--   1. schema_entities.kind ∈ {'doc_root', 'sub_entity'}
--      Distinguishes "the BankStatement type" (one per doc) from
--      "the Transaction type" (N per doc).
--   2. schema_entities.parent_type_id  uuid → schema_entities(id)
--      For sub_entity types: which doc_root type owns this collection.
--      NULL for doc_root types. Replaces the indirect path through
--      schema_relationships(kind='contains') for the common case.
--   3. inferred_schema_fields.is_repeated  boolean
--      Marks whether a field appears more than once per doc (in
--      which case it belongs to a sub_entity, not the parent).
--   4. extracted_entities.rarity_score  real
--      Migrated from atomic_units.rarity_score so the rarity / anomaly
--      retrieval channels can read from extracted_entities once
--      atomic_units is dropped at 0038.
--   5. extracted_entities.unit_type text
--      Carried over from atomic_units so the L3 plugins can stamp
--      the structural type ('transaction', 'clause', 'line_item')
--      on the child entity row. Redundant with schema_entity_id +
--      schema_entities.name, but cheap and stable across renames.
--
-- All statements idempotent. Re-applying is a no-op.

-- ============================================================================
-- schema_entities: kind + parent_type_id
-- ============================================================================

ALTER TABLE schema_entities
    ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'doc_root'
        CHECK (kind IN ('doc_root', 'sub_entity'));

ALTER TABLE schema_entities
    ADD COLUMN IF NOT EXISTS parent_type_id uuid
        REFERENCES schema_entities(id) ON DELETE CASCADE;

-- A sub_entity must have a parent_type_id; a doc_root must not.
-- Enforced via a CHECK so misuse fails loud at INSERT.
ALTER TABLE schema_entities
    DROP CONSTRAINT IF EXISTS schema_entities_parent_consistent;
ALTER TABLE schema_entities
    ADD CONSTRAINT schema_entities_parent_consistent CHECK (
        (kind = 'doc_root'   AND parent_type_id IS NULL) OR
        (kind = 'sub_entity' AND parent_type_id IS NOT NULL)
    );

-- Two indexes to make the common lookups O(log n):
--   - "give me the doc_root entity type for this doc_type name in this workspace"
--   - "give me the sub_entity types belonging to this doc_root"
CREATE INDEX IF NOT EXISTS schema_entities_workspace_kind_idx
    ON schema_entities (workspace_id, kind);
CREATE INDEX IF NOT EXISTS schema_entities_parent_idx
    ON schema_entities (parent_type_id)
    WHERE parent_type_id IS NOT NULL;


-- ============================================================================
-- inferred_schema_fields: is_repeated cardinality flag
-- ============================================================================

ALTER TABLE inferred_schema_fields
    ADD COLUMN IF NOT EXISTS is_repeated boolean NOT NULL DEFAULT false;

-- Co-occurrence cluster id — set when L2b clustering groups several
-- repeated fields together (these become the columns of one
-- sub_entity). Plain text, locally generated by the worker so we
-- don't need a separate join table.
ALTER TABLE inferred_schema_fields
    ADD COLUMN IF NOT EXISTS repeated_group text NULL;

CREATE INDEX IF NOT EXISTS inferred_schema_fields_repeated_idx
    ON inferred_schema_fields (workspace_id, inferred_doc_type, is_repeated)
    WHERE is_repeated = true;


-- ============================================================================
-- extracted_entities: rarity_score + unit_type
-- ============================================================================

ALTER TABLE extracted_entities
    ADD COLUMN IF NOT EXISTS rarity_score real
        CHECK (rarity_score IS NULL OR rarity_score >= 0);

ALTER TABLE extracted_entities
    ADD COLUMN IF NOT EXISTS unit_type text
        CHECK (unit_type IS NULL OR length(unit_type) BETWEEN 1 AND 50);

-- The atomic_units rarity index — recreated against extracted_entities
-- so the rarity / anomaly retrieval channels can swing over at 0038.
CREATE INDEX IF NOT EXISTS extracted_entities_rarity_idx
    ON extracted_entities (workspace_id, unit_type, rarity_score DESC NULLS LAST)
    WHERE rarity_score IS NOT NULL;

-- The /files/:id/sub-entities endpoint will filter by file_id + parent_entity_id IS NOT NULL.
-- Existing extracted_entities_file_idx (workspace_id-less file_id) handles file lookup.

-- Grant UPDATE on rarity_score so the centroid-recompute can write it
-- back (mirrors the atomic_units pattern). unit_type is INSERT-only.
GRANT UPDATE (lineage_path, parent_entity_id, rarity_score) ON extracted_entities TO kb_app;
